name: deploy api on push to master branch

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
      - "**.yaml"

jobs:
  update-api:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        working-directory: ./api
        run: npm ci

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          workingDirectory: ./api
          apiToken: ${{ secrets.CF_API_TOKEN }}
